name: Sync HackerRanks commit's to HackerRank-Solutions repo

on:
  push:
    branches: [ master ]

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        token: ${{ secrets.TOKEN }}
    - name: Check if Commit Message Contains '[HackerRank]'
      if : "contains(github.event.head_commit.message, 'N')"
      run : |
          git clone https://github.com/DevsExpo/FridayUB
          git remote add upstream https://github.com/StarkGang/FridayUB
          git fetch upstream
          git checkout master
          git merge upstream/master
          git push origin master
